version: '3.8'

services:
  rental-service:
    build: ./fixtures/rental-service
    ports:
      - "7001:8000"
    volumes:
      - ./logs:/shared/logs

  pricing-service:
    build: ./fixtures/pricing-service
    ports:
      - "7002:8000"
    volumes:
      - ./logs:/shared/logs

  customer-service:
    build: ./fixtures/customer-service
    ports:
      - "7003:8000"
    volumes:
      - ./logs:/shared/logs

  insurance-service:
    build: ./fixtures/insurance-service
    ports:
      - "7004:8000"
    volumes:
      - ./logs:/shared/logs


  chroma-services:
    build: ./chroma-agents/
    ports:
      - "8001:8000"
    volumes:
      - chroma-services-data:/chroma
    healthcheck:
      test: curl -f http://localhost:8000/api/v1/heartbeat || exit 1
      interval: 5s
      timeout: 3s
      retries: 5

  coordinator-agent:
    build:
      context: .
      dockerfile: coordinator_agent/Dockerfile
    depends_on:
      - chroma-services
      - rental-service
      - pricing-service
      - customer-service
    environment:
      CHROMA_AGENTS_URL: "http://chroma-services:8000"
      # point at your LM Studio on port 1234
      LMSTUDIO_URL:      "http://host.docker.internal:1234"
      # explicitly set the embed & chat paths
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/shared/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"           # host:container
    depends_on:
      - coordinator-agent
    volumes:
      - ./logs:/shared/logs

  trace-observer:
    build: ./trace-observer
    ports:
      - "9000:8000"
    volumes:
      - ./logs:/shared/logs

volumes:
  chroma-services-data:

networks:
  default:
    name: agentdemo_default
